---
managed_users: []

user_defaults:
  state: present
  shell: /bin/bash
  create_home: true
  system: false
  password_lock: false # <-- rename
  groups: []
  exclusive_keys: true

user_accounts_enable_key_mgmt: "{{ enable_ssh_key_management | default(true) }}"
user_accounts_manage_ssh_config: false
user_accounts_ssh_config_hosts: []

user_accounts_generate_keys: "{{ ssh_keys_to_generate | default([]) }}"
user_accounts_ssh_key_dir: "{{ ssh_key_dir | default(lookup('env','HOME') ~ '/.ssh') }}"
user_accounts_key_type: "{{ ssh_key_type | default('ed25519') }}"
user_accounts_key_bits: "{{ ssh_key_bits | default(4096) }}"
user_accounts_key_comment: "{{ ssh_key_comment | default('Managed by Ansible') }}"
