---
- name: Install KVM/libvirt packages
  apt:
    name: "{{ virtualization_packages }}"
    state: present
    update_cache: yes

- name: Enable and start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: true

- name: Add current user to libvirt group (optional convenience)
  user:
    name: "{{ ansible_user_id }}"
    groups: libvirt,kvm
    append: yes
  when: ansible_user_id is defined
