---
- name: Install vfio-enable
  template:
    src: vfio-enable.sh.j2
    dest: /usr/local/bin/vfio-enable
    mode: "0755"

- name: Install vfio-disable
  template:
    src: vfio-disable.sh.j2
    dest: /usr/local/bin/vfio-disable
    mode: "0755"

- name: Install vfio-status
  template:
    src: vfio-status.sh.j2
    dest: /usr/local/bin/vfio-status
    mode: "0755"

- name: Install vfio wrapper command
  template:
    src: vfio.sh.j2
    dest: /usr/local/bin/vfio
    mode: "0755"
