---
- name: Restart container service (compose v2)
  community.docker.docker_compose_v2:
    project_src: "{{ app.path }}"
    state: present
    recreate: always
  listen: "restart container service"
  when: service_state == 'present'
