---
- name: Restart container service (compose v2)
  community.docker.docker_compose_v2:
    project_src: "{{ container_service_app_path }}"
    state: present
    recreate: auto
  listen: "restart container service"
  when: service_state == 'present'
