---
- name: Deploy frontend service (stable + update)
  hosts: frontend_service
  become: true
  tags: [frontend]
  roles:
    - container_service

- name: Deploy label API service (stable + update)
  hosts: label_service
  become: true
  tags: [labelapi]
  roles:
    - container_service

- name: Deploy file service (stable + update)
  hosts: file_service
  become: true
  tags: [file]
  roles:
    - container_service

- name: Deploy manufacturing service (stable + update)
  hosts: manufacturing_service
  become: true
  tags: [manufacturing]
  roles:
    - container_service

- name: Deploy pallet service (stable + update)
  hosts: pallet_service
  become: true
  tags: [pallet]
  roles:
    - container_service

- name: Deploy product service (stable + update)
  hosts: product_service
  become: true
  tags: [product]
  roles:
    - container_service
