---
- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker_compose.yml.j2
    dest: "{{ container_service_app_path }}/docker-compose.yml"
    mode: "0644"
  register: compose_template_result
  when: service_state == 'present'
